version: '3'

services:

    app:
        build: .
        container_name: micro-videos-app
        entrypoint: dockerize -template ./.docker/app/.env:./backend/.env -template ./.docker/app/.env.testing:./backend/.env.testing -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=code_micro_videos
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
            - _DB_DATABASE_TEST=code_micro_videos_test
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - .:/var/www
        ports:
            - "3000:3000"
            - "35729:35729"    
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: micro-videos-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: micro-videos-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/mysql/init:/docker-entrypoint-initdb.d
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: micro-videos-redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
